### ISSUE TITLE
Запись на курс «Разработка программного обеспечения для GNU/Linux 2023»

### ISSUE THREAD

**Issue by FrBrGeorge** [FrBrGeorge/LinuxDevelopment2024#5]
Для получения оценки по спецкурсу «[Разработка программного обеспечения для GNU/Linux](https://uneex.org/LecturesCMC/LinuxApplicationDevelopment2023)» просьба в комментариях оставлять свои координаты в формате

-  ФИО
-  Группа (если не ВМК, то +название вуза/факультета и т. п.)
-  Ссылка на **публичный** git-репозиторий, в котором буду опубликованы решения

**Comment by s1m0000n** [comment]
- Погорельцев Семён Александрович
- 625
- https://github.com/s1m0000n/linux-app-dev-2023

**Comment by mlq45e** [comment]
- Мэн Линцянь
- 524
- https://github.com/mlq45e/DVRPOdGNULinux_dz2023

**Comment by Veniamin-Arefev** [comment]
- Арефьев Вениамин Андреевич
- 528
- https://github.com/Veniamin-Arefev/LinuxApplicationDevelopment2023

**Comment by juliazadorozhnaya** [comment]
- Задорожная Юлия Андреевна
- 530
- https://github.com/juliazadorozhnaya/LinuxApplicationDevelopment2023

**Comment by belyaevrd** [comment]
- Беляев Роман Дмитриевич
- 204
- https://github.com/belyaevrd/LinuxApplicationDevelopment2023

**Comment by yura-leb** [comment]
* Лебединский Юрий Евгеньевич
* 530
* https://github.com/yura-leb/LinuxDevelopment2023.git

**Comment by DrNightingales** [comment]
- Соловьев Петр Алексеевич
- 216
- https://github.com/DrNightingales/Gnu_Linux_Software_Development_HW

**Comment by al-romanov** [comment]
- Романов Алексей Александрович
- 527
- https://github.com/al-romanov/LinuxDevelopment2023

**Comment by PaDarochek** [comment]
- Парыгина Дарья Алексеевна
- 527
- https://github.com/PaDarochek/LinuxDevelopment2023

**Comment by SanchoMerkushev** [comment]
- Меркушев Александр Витальевич
- 528
- https://github.com/SanchoMerkushev/LinuxApp2023

**Comment by NastyaKov01** [comment]
- Коваленко Анастасия Павловна
- 624
- https://github.com/NastyaKov01/LinuxAppDev2023/tree/main

**Comment by QuantumDealer** [comment]
- Елфимова Анна Евгеньевна
- 525
- https://github.com/QuantumDealer/LinuxApplicationDevelopment2023

**Comment by Winking-maniac** [comment]
- Калинин Григорий Михайлович
- 528
- https://github.com/Winking-maniac/linux-for-applications-2023

**Comment by maxporyvay** [comment]
- Порывай Максим Викторович
- 519/2
- https://github.com/maxporyvay/LinuxApplicationDevelopment2023

**Comment by miron6** [comment]
* Миронов Денис Дмитриевич
* 619/2
* https://github.com/miron6/LinuxApplicationDevelopment2023/

**Comment by romko11l** [comment]
- Лыткин Роман Андреевич
- 619/2
- https://gitlab.com/romko11l/linuxapplicationdevelopment2023

**Comment by libsegfault** [comment]
* Панин Кирилл Игоревич
* 428
* [https://github.com/libsegfault/LinuxApplicationDevelopment2023](https://github.com/libsegfault/LinuxApplicationDevelopment2023)

**Comment by wianluna** [comment]
- Чистякова Анна Сергеевна
- 527
- https://github.com/wianluna/LinuxDevelopment2023

**Comment by ippishio** [comment]
- Тимофеев Илья Дмитриевич
- Гимназия МГУ, 11ПРОГ
- https://github.com/ippishio/LinuxApplicationDevelopment2023

**Comment by RinaRam** [comment]
Мударова Рамина Мухамедовна
630
https://github.com/RinaRam/LinuxDevelopment2023

**Comment by Symanthec** [comment]
- Резник Илья Андреевич
- Группа 216
- https://git.cs.msu.ru/s02220217/

**Comment by amoraleo** [comment]
- Морозов Леонид Алексеевич
- 619/2
- https://gitlab.com/amoraleo/linux-application-development-2023

**Comment by ValeryStupenkov** [comment]
- Ступеньков Валерий Олегович
- 525
- https://github.com/ValeryStupenkov/LinuxApplicationDevelopment2023

**Comment by Mugisius** [comment]
- Акинин Евгений Алексеевич
- 525
- https://github.com/Mugisius/LinuxApplicationDevelopment2023

**Comment by koz1ov** [comment]
* Козлов Александр Сергеевич
* 618/1
* https://github.com/koz1ov/LinuxApplicationDevelopment2023

**Comment by Litnareso** [comment]
* Демидович Евгений Владимирович
* 521
* https://git.cs.msu.ru/s02190091/linuxapplicationdevelopment2023

**Comment by rcnegby** [comment]
- Ступин Роман Евгеньевич
- 617
- https://github.com/rcnegby/linux2023

**Comment by kotopesutility** [comment]
Загайнов Данила Кириллович

**Comment by jammer312** [comment]
Косарев Григорий Тимофеевич
619/2
https://github.com/jammer312/LinuxApplicationDevelopment2023

**Comment by mishapankin** [comment]
- Панькин Михаил Михайлович
- 528
- https://github.com/mishapankin/LinuxAppDev2023

**Comment by martz-rgb** [comment]
- Воробьева Злата Витальевна
- 418
- https://git.cs.msu.ru/s02190272/linuxappdev2023

**Comment by FoggyX** [comment]
* Назаров Дмитрий Ильич
* 619/2
* https://github.com/FoggyX/LinuxApplicationDevelopment2023

**Comment by Egor-eth** [comment]
- Приходько Егор Владимирович
- 420
- https://github.com/Egor-eth/linuxappdev2023

**Comment by Natalka-Pro** [comment]
Пронина Наталия Михайловна
517
https://github.com/Natalka-Pro/linux-develop

**Comment by Dalogrom** [comment]
* Уразов Станислав Олегович
* 625
* https://github.com/Dalogrom/LinuxApplicationDevelopment2023

**Comment by mister38** [comment]
- Молотилов Никита Николаевич
 - 525
 - https://gitlab.com/mister00/linux

**Comment by gfarida** [comment]
- Гайфутдинова Фарида Хамитовна
- 527
- https://github.com/gfarida/LinuxApplicationDevelopment2023

**Comment by PetrovTimur** [comment]
- Петров Тимур Павлович
- 405
- https://github.com/PetrovTimur/LinuxApplicationDevelopment2023

**Comment by evanevanevanevannnn** [comment]
- Сухов Иван Николаевич
- 427
- https://github.com/evanevanevanevannnn/Linux2023

**Comment by berdnikovse** [comment]
- Бердников Сергей Евгеньевич
- 427
- https://github.com/berdnikovse/Unix2023

**Comment by dovvakkin** [comment]
* Кожевников Евгений Владимирович
* 624
* https://github.com/dovvakkin/LinuxApplicationDevelopment2023

**Comment by ElenaSeg** [comment]
- Егорова Елена Сергеевна 
- 530
- https://github.com/ElenaSeg/LinuxDevelopment2023

**Comment by korssm** [comment]
- Королишин Сергей Миронович
- Муром
- https://github.com/korssm/LinuxApplicationDevelopment2023

**Comment by alexmihtom** [comment]
Томшин Александр Михайлович
Рогачев
https://github.com/alexmihtom/Linux_Dev

**Comment by s02190058** [comment]
- Баканов Артём Михайлович
- 418
- https://github.com/s02190058/LinuxApplicationDevelopment2023

**Comment by RZaidullin** [comment]
Зайдуллин Ризван Рустемович
530
https://github.com/RZaidullin/Linux_fall_2023

**Comment by FrBrGeorge** [comment]
Прошлый год
